### ISSUE TITLE
wrong native extension?

### ISSUE THREAD

**Issue by phryneas** [belaviyo/send-to-vlc#1]
While the info pages redirects to the download to com.add0n.stylus, this addon seems to require the host extension com.add0n.native_client - thus it's not working.

**Comment by belaviyo** [comment]
Stylus is the project I forked the native client from. It should be "com.add0n.native_client". Can you provide info how you got "com.add0n.stylus". I just checked the code and it is "com.add0n.native_client". What is your browser?

**Comment by phryneas** [comment]
Sorry, my fault. The FAQ at https://add0n.com/send-to-vlc.html links to stylus, and only stylus - so i ended up at the wrong native extension.

**Comment by belaviyo** [comment]
I see, I modified that FAQs page to point to the right place. Thanks!

**Comment by phryneas** [comment]
btw.: works fine, thanks for the great addon :)
