### ISSUE TITLE
Repository hasn't been updated in almost a year

### ISSUE THREAD

**Issue by veikk0** [belaviyo/send-to-vlc#17]
There have been [multiple updates](https://addons.mozilla.org/en-US/firefox/addon/send-to-vlc-videolan-player/versions/) to this add-on and [the MPV variant](https://addons.mozilla.org/en-US/firefox/addon/send-to-mpv-player/versions/) in 2018 but they haven't been pushed to the repo. I know you can probably extract the files from the .xpi and manually compare but that's just a bit too convoluted way of seeing what changed from version to version.

I was curious what really changed between the MPV edition 0.1.2 and 0.1.3 to justify the new permission to access browser history. This is what lead me to discover that the repo is out of date.

I also noticed that while the addons.mozilla.org page states the add-on is released under the MPL 2.0 the repo doesn't actually mention the license at all, which could discourage forking.

**Comment by belaviyo** [comment]
True. Just updated the repo to the latest release. Thanks for the heads up.

> I was curious what really changed between the MPV edition 0.1.2 and 0.1.3 to justify the new permission to access browser history.

see https://github.com/belaviyo/send-to-vlc/issues/15

> the repo doesn't actually mention the license at all

done
