### ISSUE TITLE
Handling messages from other extensions

### ISSUE THREAD

**Issue by pgasior** [belaviyo/send-to-vlc#19]
Can you add support for listening for messages from other extensions? I created addon that added "Send to ..." as button to links on page for convenience. Only problem is that your extension doesn't handle messages from other extensions.

I temporarily added onMessageExternal listener to your extension and it works as expected
```js
chrome.runtime.onMessageExternal.addListener((request, sender) => {
  if (request.method === 'send-to-vlc') {
    sendToVLC(request.urls);
  }
})
```

This would be very helpful, as I wouldn't need to copy-paste your extension into mine and modify native-client manifest.

**Comment by belaviyo** [comment]
We are going to support this on the next release;
```js
chrome.runtime.sendMessage('extension id here', {
  method: 'play',
  passphrase: 'a shared passphrase',
  urls: ['url-1', 'url-2', ...]
})
```
