### ISSUE TITLE
send-to-youtubedl? send-to-mpv with more options before?

### ISSUE THREAD

**Issue by cyberpunkbln** [belaviyo/send-to-vlc#2]
Hello,

great addon. Is it possible to bring up an directly youtube-dl addon? I think must not the problem, like the others but i search for an addon that bring up an Layer with options that has youtube-dl sniffed for himself and sniffed for mpv. I mean that i can choose some more options like quality and so on?

thx

**Comment by belaviyo** [comment]
Either go to the options page and change the command to point to the yt-dl executable or use Andy's "External Application Button" extension.

**Comment by cyberpunkbln** [comment]
Thx, but this Extension is not an WebExtension-App but the change the command is an option. In the newest Firefox version addons must be coded with WebExtensions-NativeMessaging-Api to call an external app, that broke all old addons. Only one NativeMessaging-Client can be active i think and i will be on your NativeClient-Implementation with nodejs.

**Comment by cyberpunkbln** [comment]
Sorry i have found the old application now i have found the external app button with WebExtensions:)
