### ISSUE TITLE
Error: spawn exec ENOENT

### ISSUE THREAD

**Issue by grahamperrin** [belaviyo/send-to-vlc#4]
Found when, for example, trying to send the video at https://www.youtube.com/watch?v=qvuhlrKikOc

![2017-09-23 13 05 52](https://user-images.githubusercontent.com/192271/30773082-38aaa7da-a061-11e7-8be5-670e37fff003.png)

In preferences for the extension, I specify this command: 

`exec vlc`

– which does execute VLC (launch its GUI etc.) when run from a terminal window. Do I need a variation on that command?

**Comment by andy-portmen** [comment]
I think you just need to have just `vlc`. There is no need for that `exec` command.

**Comment by andy-portmen** [comment]
The error message you get means that there is no file named exec.

**Comment by grahamperrin** [comment]
Thanks. That's enough to close this issue. 

(The resulting `/tmp/vlc-3363408419.m3u8` is zero bytes, I'll tackle that later.)

**Comment by skanskan** [comment]
I have the same error, and my command is just vlc.exe (with the path)
