### ISSUE TITLE
he external media player is not found. please make sure the path in the optios page is correct

### ISSUE THREAD

**Issue by AzuKaOwO** [belaviyo/send-to-vlc#41]
![image](https://user-images.githubusercontent.com/60112822/103786834-2e99f180-503d-11eb-8175-c406dde26be1.png)

**Comment by AzuKaOwO** [comment]
![Uploading image.png…]()

**Comment by AzuKaOwO** [comment]
i tried all existing path

**Comment by pigsflew** [comment]
Your path needs to start with a drive (e.g. `C:\`), e.g. `"C:\Program Files (x86)\VideoLAN\VLC\vlc.exe"`

If you didn't install it to a custom location, you can leave this field blank.
