### ISSUE TITLE
'One more step' Page Keeps Opening at Random

### ISSUE THREAD

**Issue by FunkyDarkKnight** [belaviyo/send-to-vlc#6]
[Note: I'm only using 'Send To MPV']

I have no complaints with the functionality of the add-on as it works perfectly. My issue is that every few times I use it to open a video from a webpage it will occasionally flash up the 'one more step' page that prompts me to install the client. I already installed the client ages ago, as evidenced by the fact that the videos play perfectly.

Could there be an option to please disable this 'One more step' page from showing up altogether when you're sure the extension is working fine?

Cheers!

Oh and as a side request - could we also have the option to disable the number that shows up on the icon on the toolbar? I prefer to disable number badges on my add-ons where possible for a cleaner looking toolbar, I generally don't have any use for them anyway.

**Comment by belaviyo** [comment]
We have a few new options in the options page to accomplish both.

**Comment by FunkyDarkKnight** [comment]
I cannot find these options - is this for an upcoming version? Keep in mind I'm only using Send to MPV so I won't know if it's only been implemented in the other 'Sent To' programs.

**Comment by belaviyo** [comment]
What is your browser?

**Comment by FunkyDarkKnight** [comment]
Firefox Beta (Quantum) - but this was occurring with the stable branch as well.

**Comment by belaviyo** [comment]
https://addons.mozilla.org/en-US/firefox/addon/send-to-mpv-player/versions/

**Comment by FunkyDarkKnight** [comment]
Thank you very much!
