### ISSUE TITLE
[Feature Request] Stop MPV Closing When Browser Is Closed

### ISSUE THREAD

**Issue by FunkyDarkKnight** [belaviyo/send-to-vlc#7]
Not sure if this is possible or not, but it would be neat to have the option for MPV to stay open when the browser is closed.

For example, I like to load up playlists into MPV with hours worth of videos and it would be nice if I didn't need the browser running the entire time.

Thanks again for quickly responding to and fixing my previous issue, by the way! 👍

[Running Firefox Quantum, for reference]

**Comment by KotKod** [comment]
Did you try add to custom command  `--keep-open=yes` ?
