### ISSUE TITLE
[Feature request] Shortcut

### ISSUE THREAD

**Issue by xorob0** [belaviyo/send-to-vlc#9]
I don't know what shortcut to bind it with but it would be nice to stop having to click on th addon icon everytime you want to play a video.

**Comment by bwakkie** [comment]
How about to leave the shortcut key to the user settings with a default to 'F1'?

**Comment by v0idpwn** [comment]
I'm not sure if F1 is a good default, as F1 is generally a help key

**Comment by bwakkie** [comment]
Agreed, how about 'p' from play?

**Comment by indeedwatson** [comment]
Would interfere with some websites' shortcuts, but regardless, I find this discussion a bit pointless when the feature itself hasn't been addressed or promised, or we even know if it's possible due to how the new webextension system works.
